#!/bin/sh

SCRIPT_PATH=$(dirname $0)

test_files=$(find ${SCRIPT_PATH}/tests -name '*.esl')
echo $test_files

for test in $test_files; do
    printf "\ntest \e[1m$test\e[m\n\n"
    $SCRIPT_PATH/build/bootstrap/esl $test
done
