[package]
name = "elc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
argparse = "0.2.2"
dirs = "6.0.0"
env_logger = "0.11.8"
log = "0.4.28"
scopeguard = "1.2.0"
tempfile = "3.16.0"
typed-arena = "2.0.2"
